// ========================================================
// FloristEver - Configuração Oficial das Flores
// ========================================================
import { PALETTE } from '../utils.js';

export const FLOWERS_CONFIG = {
  daisy: {
    id: 'daisy',
    name: 'Margarida',
    meaning: 'Pureza, inocência e novos começos',
    requiredLevel: 1,
    growthTime: 8, // segundos
    value: 5, // moedas por unidade
    unlockCost: 0, // desbloqueada de início
    unlockedByDefault: true,
    color: '#FFFDF0',
    centerColor: PALETTE.sunYellow,
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 8,
    radius: 13,
    icon: '🌼',
    plotBaseCost: 50,
    stockSkillCost: 350,
    stockMinimum: 6,
    shortDescription: 'Flor campestre alegre e resistente que floresce rapidamente.'
  },
  tulip: {
    id: 'tulip',
    name: 'Tulipa',
    meaning: 'Afeto sincero, carinho e gratidão',
    requiredLevel: 2,
    growthTime: 15,
    value: 12,
    unlockCost: 150,
    unlockedByDefault: false,
    color: PALETTE.peonyPink,
    centerColor: '#E0577D',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 3,
    radius: 14,
    icon: '🌷',
    plotBaseCost: 150,
    stockSkillCost: 700,
    stockMinimum: 5,
    shortDescription: 'Cálice elegante com tons de rosa primaveril.'
  },
  sunflower: {
    id: 'sunflower',
    name: 'Girassol',
    meaning: 'Luz, vitalidade, calor e prosperidade',
    requiredLevel: 3,
    growthTime: 25,
    value: 30,
    unlockCost: 600,
    unlockedByDefault: false,
    color: PALETTE.sunYellow,
    centerColor: PALETTE.earthBrown,
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 12,
    radius: 17,
    icon: '🌻',
    plotBaseCost: 600,
    stockSkillCost: 1400,
    stockMinimum: 4,
    shortDescription: 'Grande e reluzente como o sol da tarde.'
  },
  rose: {
    id: 'rose',
    name: 'Rosa',
    meaning: 'Amor apaixonado, elegância e romance',
    requiredLevel: 5,
    growthTime: 40,
    value: 75,
    unlockCost: 2000,
    unlockedByDefault: false,
    color: PALETTE.raspberryPink,
    centerColor: '#AA264A',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 6,
    radius: 15,
    icon: '🌹',
    plotBaseCost: 2000,
    stockSkillCost: 3000,
    stockMinimum: 3,
    shortDescription: 'A rainha dos jardins com camadas aveludadas de pétalas.'
  },
  orchid: {
    id: 'orchid',
    name: 'Orquídea',
    meaning: 'Raridade, beleza sublime e sofisticação',
    requiredLevel: 8,
    growthTime: 70,
    value: 200,
    unlockCost: 8000,
    unlockedByDefault: false,
    color: PALETTE.lavender,
    centerColor: '#6B4E9B',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 5,
    radius: 16,
    icon: '💮',
    plotBaseCost: 8000,
    stockSkillCost: 6500,
    stockMinimum: 2,
    shortDescription: 'Exótica e preciosa flor lilás com perfume delicado.'
  },
  lavender: {
    id: 'lavender',
    name: 'Lavanda',
    meaning: 'Serenidade, cuidado e lembranças tranquilas',
    requiredLevel: 10,
    growthTime: 50,
    value: 110,
    unlockCost: 5000,
    unlockedByDefault: false,
    color: '#B39DDB',
    centerColor: '#F7C948',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    shape: 'spike',
    petals: 9,
    radius: 14,
    icon: '🪻',
    plotBaseCost: 12000,
    stockSkillCost: 4800,
    stockMinimum: 3,
    shortDescription: 'Espigas lilases e perfumadas para ramos serenos.'
  },
  peony: {
    id: 'peony',
    name: 'Peónia',
    meaning: 'Prosperidade, ternura e beleza generosa',
    requiredLevel: 12,
    growthTime: 100,
    value: 260,
    unlockCost: 9000,
    unlockedByDefault: false,
    color: '#F1A6C1',
    centerColor: '#B8476C',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 16,
    radius: 18,
    icon: '🏵️',
    plotBaseCost: 18000,
    stockSkillCost: 9000,
    stockMinimum: 2,
    shortDescription: 'Uma flor volumosa em tons rosados, de presença marcante.'
  },
  camellia: {
    id: 'camellia',
    name: 'Camélia',
    meaning: 'Admiração, elegância e afeto duradouro',
    requiredLevel: 14,
    growthTime: 120,
    value: 320,
    unlockCost: 18000,
    unlockedByDefault: false,
    color: '#F2A5A0',
    centerColor: '#F6D66B',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 10,
    radius: 17,
    icon: '🎀',
    plotBaseCost: 18000,
    stockSkillCost: 10000,
    stockMinimum: 3,
    shortDescription: 'Pétalas arredondadas e delicadas, símbolo de estima e elegância.'
  },
  iris: {
    id: 'iris',
    name: 'Íris',
    meaning: 'Esperança, sabedoria e boas notícias',
    requiredLevel: 16,
    growthTime: 140,
    value: 360,
    unlockCost: 22000,
    unlockedByDefault: false,
    color: '#8270D5',
    centerColor: '#F4C95D',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 6,
    radius: 17,
    petalShape: 'heart',
    icon: '🔷',
    plotBaseCost: 22000,
    stockSkillCost: 11000,
    stockMinimum: 3,
    shortDescription: 'Flor roxa de pétalas amplas, inspirada nos jardins clássicos.'
  },
  jasmine: {
    id: 'jasmine',
    name: 'Jasmim',
    meaning: 'Doçura, serenidade e boas recordações',
    requiredLevel: 17,
    growthTime: 160,
    value: 400,
    unlockCost: 26000,
    unlockedByDefault: false,
    color: '#FFF9E8',
    centerColor: '#F5D76E',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 7,
    radius: 13,
    icon: '🤍',
    plotBaseCost: 26000,
    stockSkillCost: 12000,
    stockMinimum: 3,
    shortDescription: 'Pequenas flores claras, perfumadas e delicadas.'
  },
  gardenia: {
    id: 'gardenia',
    name: 'Gardénia',
    meaning: 'Gratidão, confiança e gentileza',
    requiredLevel: 18,
    growthTime: 180,
    value: 450,
    unlockCost: 30000,
    unlockedByDefault: false,
    color: '#FFFAE9',
    centerColor: '#F0D18A',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 9,
    radius: 16,
    icon: '🕊️',
    plotBaseCost: 30000,
    stockSkillCost: 13000,
    stockMinimum: 3,
    shortDescription: 'Flor branca em camadas, elegante e muito apreciada em agradecimentos.'
  },
  anemone: {
    id: 'anemone',
    name: 'Anémona',
    meaning: 'Expectativa, leveza e proteção',
    requiredLevel: 19,
    growthTime: 195,
    value: 480,
    unlockCost: 34000,
    unlockedByDefault: false,
    color: '#E97891',
    centerColor: '#292C42',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 8,
    radius: 16,
    icon: '🌟',
    plotBaseCost: 34000,
    stockSkillCost: 14000,
    stockMinimum: 3,
    shortDescription: 'Pétalas vivas em torno de um centro escuro e contrastante.'
  },
  dahlia: {
    id: 'dahlia',
    name: 'Dália',
    meaning: 'Criatividade, dignidade e diversidade',
    requiredLevel: 21,
    growthTime: 200,
    value: 500,
    unlockCost: 38000,
    unlockedByDefault: false,
    color: '#E86F9A',
    centerColor: '#F2CF6E',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 14,
    radius: 18,
    icon: '💐',
    plotBaseCost: 38000,
    stockSkillCost: 15000,
    stockMinimum: 3,
    shortDescription: 'Flor cheia e colorida, ideal para composições exuberantes.'
  },
  chrysanthemum: {
    id: 'chrysanthemum',
    name: 'Crisântemo',
    meaning: 'Alegria, amizade e vida longa',
    requiredLevel: 22,
    growthTime: 220,
    value: 540,
    unlockCost: 42000,
    unlockedByDefault: false,
    color: '#F4A849',
    centerColor: '#A94832',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 16,
    radius: 17,
    icon: '🌿',
    plotBaseCost: 42000,
    stockSkillCost: 16000,
    stockMinimum: 3,
    shortDescription: 'Muitas pétalas quentes para ramos alegres e generosos.'
  },
  foxglove: {
    id: 'foxglove',
    name: 'Dedaleira',
    meaning: 'Encanto, imaginação e mistério',
    requiredLevel: 23,
    growthTime: 240,
    value: 580,
    unlockCost: 46000,
    unlockedByDefault: false,
    color: '#B875C9',
    centerColor: '#F5D98B',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    shape: 'spike',
    petals: 8,
    radius: 17,
    icon: '🔔',
    plotBaseCost: 46000,
    stockSkillCost: 17000,
    stockMinimum: 2,
    shortDescription: 'Espiga de flores em forma de sino, rara e cheia de personalidade.'
  },
  verbena: {
    id: 'verbena',
    name: 'Verbena',
    meaning: 'Harmonia, inspiração e bons desejos',
    requiredLevel: 24,
    growthTime: 255,
    value: 610,
    unlockCost: 50000,
    unlockedByDefault: false,
    color: '#9C75D1',
    centerColor: '#F1D36C',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 6,
    radius: 15,
    icon: '💜',
    plotBaseCost: 50000,
    stockSkillCost: 18000,
    stockMinimum: 3,
    shortDescription: 'Pequenas flores violetas que dão cor a qualquer arranjo.'
  },
  hydrangea: {
    id: 'hydrangea',
    name: 'Hortênsia',
    meaning: 'Compreensão, abundância e gratidão',
    requiredLevel: 25,
    growthTime: 275,
    value: 660,
    unlockCost: 54000,
    unlockedByDefault: false,
    color: '#78A9E8',
    centerColor: '#F4D978',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 12,
    radius: 18,
    icon: '🔵',
    plotBaseCost: 54000,
    stockSkillCost: 19000,
    stockMinimum: 2,
    shortDescription: 'Conjunto arredondado de flores azuis, perfeito para ramos volumosos.'
  },
  lotus: {
    id: 'lotus',
    name: 'Lótus',
    meaning: 'Renovação, equilíbrio e serenidade',
    requiredLevel: 28,
    growthTime: 295,
    value: 700,
    unlockCost: 60000,
    unlockedByDefault: false,
    color: '#F39BC2',
    centerColor: '#F5D76E',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 10,
    radius: 19,
    icon: '🪷',
    plotBaseCost: 60000,
    stockSkillCost: 20000,
    stockMinimum: 2,
    shortDescription: 'Pétalas largas e luminosas, inspiradas nos jardins aquáticos.'
  },
  magnolia: {
    id: 'magnolia',
    name: 'Magnólia',
    meaning: 'Nobreza, perseverança e beleza natural',
    requiredLevel: 29,
    growthTime: 320,
    value: 760,
    unlockCost: 66000,
    unlockedByDefault: false,
    color: '#F5DCE0',
    centerColor: '#E6B45C',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 7,
    radius: 19,
    icon: '🌙',
    plotBaseCost: 66000,
    stockSkillCost: 21000,
    stockMinimum: 2,
    shortDescription: 'Pétalas amplas em tons suaves, uma presença nobre no jardim.'
  },
  protea: {
    id: 'protea',
    name: 'Proteia',
    meaning: 'Coragem, transformação e originalidade',
    requiredLevel: 30,
    growthTime: 345,
    value: 820,
    unlockCost: 72000,
    unlockedByDefault: false,
    color: '#E88F71',
    centerColor: '#8E5261',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 11,
    radius: 19,
    petalShape: 'heart',
    icon: '🔶',
    plotBaseCost: 72000,
    stockSkillCost: 22000,
    stockMinimum: 2,
    shortDescription: 'Uma flor escultural e exótica para arranjos memoráveis.'
  },
  ranunculus: {
    id: 'ranunculus',
    name: 'Ranúnculo',
    meaning: 'Charme, alegria e encanto',
    requiredLevel: 31,
    growthTime: 365,
    value: 870,
    unlockCost: 78000,
    unlockedByDefault: false,
    color: '#F58B5D',
    centerColor: '#F4D06B',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 18,
    radius: 18,
    icon: '🧡',
    plotBaseCost: 78000,
    stockSkillCost: 23000,
    stockMinimum: 2,
    shortDescription: 'Camadas densas de pétalas para celebrações e presentes especiais.'
  },
  alstroemeria: {
    id: 'alstroemeria',
    name: 'Alstroeméria',
    meaning: 'Amizade, devoção e novos caminhos',
    requiredLevel: 32,
    growthTime: 390,
    value: 920,
    unlockCost: 84000,
    unlockedByDefault: false,
    color: '#F29A75',
    centerColor: '#E6CB66',
    stemColor: PALETTE.leafGreen,
    outlineColor: PALETTE.deepGreen,
    petals: 6,
    radius: 17,
    icon: '🌈',
    plotBaseCost: 84000,
    stockSkillCost: 24000,
    stockMinimum: 2,
    shortDescription: 'Pétalas em tons quentes que completam ramos de várias espécies.'
  }
};

// Ordem canónica de progressão das flores
export const FLOWER_ORDER = [
  'daisy',
  'tulip',
  'sunflower',
  'rose',
  'orchid',
  'lavender',
  'peony',
  'camellia',
  'iris',
  'jasmine',
  'gardenia',
  'anemone',
  'dahlia',
  'chrysanthemum',
  'foxglove',
  'verbena',
  'hydrangea',
  'lotus',
  'magnolia',
  'protea',
  'ranunculus',
  'alstroemeria'
];

// Calcula o custo da n-ésima parcela comprada da mesma flor: base * 1.6^n
export function getPlotCost(flowerId, plotsAlreadyOwned = 0) {
  const cfg = FLOWERS_CONFIG[flowerId];
  if (!cfg) return 100;
  return Math.round(cfg.plotBaseCost * Math.pow(1.6, plotsAlreadyOwned));
}
